services:
  - type: web
    name: campus-navigator
    runtime: docker
    plan: free
    region: oregon
    branch: main

    healthCheckPath: /api/health

    envVars:
      - key: APP_NAME
        value: Campus Navigator

      - key: APP_ENV
        value: production

      - key: APP_DEBUG
        value: false

      - key: APP_KEY
        generateValue: true

      - key: APP_URL
        value: https://campus-navigator-renk.onrender.com

      # DB
      - key: DB_CONNECTION
        value: mysql

      - key: DB_HOST
        fromDatabase:
          name: campus-navigator-db
          property: host

      - key: DB_PORT
        fromDatabase:
          name: campus-navigator-db
          property: port

      - key: DB_DATABASE
        fromDatabase:
          name: campus-navigator-db
          property: database

      - key: DB_USERNAME
        fromDatabase:
          name: campus-navigator-db
          property: user

      - key: DB_PASSWORD
        fromDatabase:
          name: campus-navigator-db
          property: password

      # CACHE (safe mode first)
      - key: CACHE_DRIVER
        value: file

      - key: SESSION_DRIVER
        value: file

      - key: QUEUE_CONNECTION
        value: sync

      # Redis (add AFTER deployment works)
      - key: REDIS_HOST
        fromService:
          name: campus-navigator-redis
          type: redis
          property: host

      - key: REDIS_PORT
        value: 6379

      - key: REDIS_URL
        fromService:
          name: campus-navigator-redis
          type: redis
          property: connectionString

databases:
  - name: campus-navigator-db
    databaseName: campus_navigator
    plan: free

services:
  - type: redis
    name: campus-navigator-redis
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: allow all