services:
  - type: web
    name: campus-navigator
    runtime: php
    plan: free
    region: oregon
    branch: main

    healthCheckPath: /api/health

    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate

    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT

    envVars:
      - key: APP_NAME
        value: Campus Navigator API

      - key: APP_ENV
        value: production

      - key: APP_DEBUG
        value: false

      - key: APP_KEY
        generateValue: true

      - key: APP_URL
        value: https://campus-navigator.onrender.com

      - key: LOG_CHANNEL
        value: stdout

      - key: LOG_LEVEL
        value: error

      # DATABASE
      - key: DB_CONNECTION
        value: mysql

      - key: DB_HOST
        fromDatabase:
          name: campus-navigator-db
          property: host

      - key: DB_PORT
        fromDatabase:
          name: campus-navigator-db
          property: port

      - key: DB_DATABASE
        fromDatabase:
          name: campus-navigator-db
          property: database

      - key: DB_USERNAME
        fromDatabase:
          name: campus-navigator-db
          property: user

      - key: DB_PASSWORD
        fromDatabase:
          name: campus-navigator-db
          property: password

      # REDIS
      - key: CACHE_DRIVER
        value: redis

      - key: SESSION_DRIVER
        value: redis

      - key: QUEUE_CONNECTION
        value: redis

      - key: REDIS_HOST
        fromService:
          name: campus-navigator-redis
          type: redis
          property: host

      - key: REDIS_PORT
        fromService:
          name: campus-navigator-redis
          type: redis
          property: port

      - key: REDIS_PASSWORD
        fromService:
          name: campus-navigator-redis
          type: redis
          property: password

      # JWT
      - key: JWT_SECRET
        generateValue: true

      - key: JWT_TTL
        value: 60

      # CORS
      - key: SANCTUM_STATEFUL_DOMAINS
        value: localhost,127.0.0.1

      - key: SESSION_DOMAIN
        value: .onrender.com

  # REDIS SERVICE 
  - type: redis
    name: campus-navigator-redis
    plan: free

# DATABASE 
databases:
  - name: campus-navigator-db
    databaseName: campus_navigator
    plan: free